### ISSUE TITLE
[ADD] teams - 팀 참가 API 연결

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#118]
## 💡 Issue

EnterHouse에서 사용할 팀 참가 API를 연결합니다.

## 📝 Todo

- [x]  postTeam Router 생성
- [x]  postJoinTeam API 생성
- [x] EnterHouse에 POST 연결 -> HouseInfo로 이동
- [x] 이미 속한 팀이 있을 때 예외처리
- [x] 참가 요청한 팀 id에 해당하는 팀이 존재하지 않을 때 예외처리
- [x] 요청한 초대코드의 만료 시간(5분)이 지났을 때 예외처리
- [x] 요청한 초대 코드가 일치하지 않을 때 예외처리
- [x] Base Padding Label 구현
