### ISSUE TITLE
[FEAT] 홈뷰 상단 데이터 바인딩

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#122]
## 💡 Issue

<img width="559" alt="스크린샷 2023-03-30 오후 3 47 53" src="https://user-images.githubusercontent.com/83629193/228752369-51e0ad46-d4ae-42b4-89ee-47fb3a92d29e.png">
홈뷰 상단의 데이터를 서버 데이터로 바인딩할 예정입니다.

## 📝 Todo

- [x] 이미 개발된 API, Router 파일 체크
- [x] 집안일 참여자 이름, 이번주 끝낸 집안일 갯수 데이터 바인딩
- [x] 집안일 참여자 이미지 로딩 
- [x] 집안일 참여자 터치시 해당 참여자 기준으로 데이터 정렬
- [x] 규칙 데이터 보여주기
