### ISSUE TITLE
[ADD] teams - 팀 업데이트 API 연결

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#124]
## 💡 Issue

- 설정 >  하우스이름 변경
- 팀 업데이트 API를 연결합니다.

## 📝 Todo

- [x] patchTeamInfo Router, patchTeamInfo API 추가
- [x] 설정 > 하우스 이름 변경 push 구현
- [x] 하우스 이름 변경에서 입력 완료 선택 시 pop과 함께 patch 진행
