### ISSUE TITLE
[ADD] teams - 팀 나가기 API 연결

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#133]
## 💡 Issue

- 팀 나가기에 대한 POST API를 연결합니다.

## 📝 Todo

- [x] postLeaveTeam Router, postLeaveTeam API 구현
- [x] 설정 > 팀 나가기 버튼 선택 시 모달 노출
- [x] 모달 > 확인 버튼 선택 시 팀 나가기 진행
- [x] 팀 나가기 이후 팀 만들기, 참여 뷰로 이동
