### ISSUE TITLE
[FEAT] Apple Login

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#143]
## 💡 Issue

 - 애플 로그인 구현

## 📝 Todo

- [ ] 애플 로그인에 필요한 환경 설정
- [ ] 애플 로그인 버튼 추가
- [ ] 로그인 확인
- [ ] 로그인 시도 중 백그라운드 이동 시 에러 처리

## 📬 Reference

- [https://developer.apple.com/documentation/sign_in_with_apple]()
