### ISSUE TITLE
[ADD] OnboardingProfileView 생성

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#16]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/190972165-a2010efa-a7e7-4649-9600-2df636fa2ba5.png"/>|<img src="https://user-images.githubusercontent.com/81340603/190972264-88cb724d-e14d-4f5e-8028-b0b4a9ce6dd9.png"/>|
|-|-|
OnboardingProfileView UI & Logic 만들기

## 📝 Todo
- [x] Asset 추가 (프로필 이미지(default), 회색 원형 이미지, 뒤로가기 버튼)
- [x] 상단, 중앙 라벨
- [x] 사진 ImageView 영역
- [x] 4x4 Collection View
- [x] 하단 mainbutton (CTA)
- [x] 사진 눌렀을 경우 이미지 변경
- [x] 사진 눌렀을 경우 cell에 원형 테두리 추가하기

## 📬 Reference

- https://ios-development.tistory.com/972
