### ISSUE TITLE
[FEAT] 공간 선택 컬렉션 뷰 만들기

### ISSUE THREAD

**Issue by dangsal** [fairer-iOS/fairer-iOS#17]
## 💡 Issue

- 집안일 생성(추가) 뷰 UI 생성

## 📝 Todo

- [ ] 날짜 누르는 버튼 만들기
- [x] 공간을 선택하는 컬렉션 뷰 만들기
- [ ] 설명 레이블 만들기
- [ ] 집안일 직접 입력 버튼 만들기
- [ ] CTA버튼 생성
- [ ] 세부 집안일 컬렉션뷰 만들기
- [ ] 같은 공간이 아닐 시 알럿창 생성
- [ ] 

## 📬 Reference

- []()
