### ISSUE TITLE
[ADD] 집안일 생성/수정 화면 - 데이터 바인딩 

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#182]
## 💡 Issue
집안일 생성/수정 화면은 연결되어 있으나
데이터가 전달되지 않고 있습니다.
화면에 load 되었을 때 적절한 데이터가 init 될 수 있게 데이터를 바인딩합니다.

## 📝 Todo
- [ ] HomeVC -> EditHouseWorkVC : 기존 집안일 데이터 바인딩
- [ ] SelectHouseWorkVC -> SetHouseWorkVC : 공간 데이터 바인딩
- [ ] 전체 화면 점검
