### ISSUE TITLE
[FEAT] 닉네임 정렬 + 글자수 제한 핸들링

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#194]
## 💡 Issue
1) 유저 본인 > ㄱㄴㄷ 순 닉네임 정렬
2) 한글 닉네임 (4글자) 까지 완전히 표시 > 5번째 글자는 ...으로 표시  

## 📝 Todo
- [x] HomeViewController - ㄱㄴㄷ 순 닉네임 정렬
- [x] HomeViewController - 닉네임 글자수 제한
- [x] SetHouseWorkViewController - 유저 본인 > ㄱㄴㄷ 순으로 닉네임 정렬
- [x] SetHouseWorkViewController - 닉네임 글자수 제한
- [x] WriteHouseWorkViewController - 유저 본인 > ㄱㄴㄷ 순으로 닉네임 정렬
- [x] WriteHouseWorkViewController - 닉네임 글자수 제한
- [x] HouseInfoViewController - ㄱㄴㄷ 으로 닉네임 정렬
- [x] HouseInfoViewCotroller - 닉네임 글자수 제한
