### ISSUE TITLE
[FIX] 버그 테이블 버그, 디버깅

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#209]
## 💡 Issue

- 버그 테이블 버그, 디버깅

## 📝 Todo

- [x] 화면 로드 후 (오늘) 반영 안되는 문제
- [x] 하루종일 라벨 추가
- [x] 홈의 자잘자잘 UI 수정
