### ISSUE TITLE
[FIX] 하우스 이름 textfield에 하우스 이름 text 추가

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#225]
## 💡 Issue

[하우스 이름 textfield에 하우스 이름 text 추가](https://www.notion.so/textfield-text-d8a222034838495ab83841de62ac8159) 이슈를 해결합니다

## 📝 Todo
- [x] 하우스 정보 api 연결
- [x] textfield 이름 추가
- [x] 특수문자 핸들링
- [x] 16자 초과 핸들링
- [x] 변경 사항 있고 특수문자 없고 16자 이내인 경우 입력완료 버튼 활성화
