### ISSUE TITLE
[FIX] QA 사항 반영

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#229]
## 💡 Issue

- QA 사항 반영

## 📝 Todo

- [x] 집안일 추가 버튼 background view top padding  조정하기
- [x] 당일 시간이 지나지 않았는데, 지났다는 버그
- [x] 설정 하우스 관리 카카오 공유하기 API 연결
- [ ] 다른 유저 프로필 선택 후 집안일 추가하면 필터링 오류 발생
- [ ] 집안일 모두 완료 empty view 추가
