### ISSUE TITLE
[FEAT] 회원 탈퇴 api 연결 및 유저 디폴트 버그 해결

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#250]
## 💡 Issue
- 로그아웃 api 를 연결합니다.
- 회원 탈퇴 api 를 연결합니다.
- 유저 디폴트 버그를 해결합니다.

## 📝 Todo

- [ ] 로그아웃 api 를 연결합니다.
- [ ] 회원 탈퇴 api 를 연결합니다.
- [ ] 유저 디폴트 버그를 해결합니다.
