### ISSUE TITLE
[ADD] GroupMainView 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#26]
## 💡 Issue
![그룹 생성, 참여 (1)](https://user-images.githubusercontent.com/81340603/192260690-006b5d45-d20e-4567-9b98-5637cd1648e3.png)

## 📝 Todo
- [x] 디렉토리 생성 & 어셋 추가
- [x] 상위 라벨
- [x] 버튼 라벨 & 버튼
- [x] 하단 경고 라벨 Component로 만들기
- [x] LoginView 머지된 거 pull 받아서 lineheight extension 적용하기
