### ISSUE TITLE
[FEAT] 피드백 - 캡슐 UI 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#272]
## 💡 Issue

<img width="315" alt="스크린샷 2023-09-18 오후 8 15 27" src="https://github.com/fairer-iOS/fairer-iOS/assets/81340603/f6462dd3-a532-4d9f-b61d-e1863afc4121">
박스 처리된 영역을 구현합니다.

## 📝 Todo

- [x] CollectionView Cell 생성
- [x] UICollectionViewFlowLayout 쓸지, UICollectionViewCompositionalLayout 쓸지 고민
- [x] 결정되면 CollectionView 생성
- [x] DailyCollectionViewCell 아래에 넣기
