### ISSUE TITLE
[ADD] HouseMakeNameView UI & Logic 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#32]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/192959378-db91294b-86d6-4f1d-a92f-12710ee01f5b.png"/>|<img src="https://user-images.githubusercontent.com/81340603/192959396-4c7ea012-d706-4d01-8765-807b058facff.png"/>|
|-|-|

## 📝 Todo
- [x] Primary & Secondary 라벨
- [x] TextField 추가 (여러 로직도 한 번에 적용)
- [x] MainButton으로 CTA 버튼 적용
