### ISSUE TITLE
[ADD] HouseInviteCodeView UI & Logic 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#34]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/193840054-4bb2ddc8-64be-4f48-a3fe-4acac73003d1.png"/>|<img src="https://user-images.githubusercontent.com/81340603/193840118-877bf749-5c69-4083-8de0-7daa7b0e2efe.png"/>|<img src="https://user-images.githubusercontent.com/81340603/194697702-6247d03f-14d4-46d7-8a8c-d0d523f288fc.png" />|
|-|-|-|

## 📝 Todo
- [x] Directory & 파일 생성
- [x] 사진 asset 추가
- [x] 상단 라벨
- [x] 초대 코드 뷰
- [x] 유효 코드 라벨, Info 라벨
- [x] 이미지 있는 버튼 2 개 -> UIComponent
- [x] 텍스트 버튼 1개
- [x] 코드 복사 구현
- [x] 토스트 팝업
- [x] 하단 버튼 3 개 view 로 빼기
- [x] 시간에 따라 분기처리 하기 (코드 만료 기준)
