### ISSUE TITLE
[ADD] EnterHouseView UI

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#36]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/195974482-cee5ce3e-2798-4179-b0a5-389dfe0ac715.png" />|<img src="https://user-images.githubusercontent.com/81340603/195974487-de3e5904-66b1-4d12-a433-a0901a7aba1b.png"/>|<img src="https://user-images.githubusercontent.com/81340603/195974490-5d85b234-3f92-414f-93d5-d4a938a8b3ed.png"/>|
|:---:|:---:|:---:|
|<center>default</center>|<center>잘못된 코드</center>|<center>최대 인원</center>|

## 📝 Todo
- [x] 기본 세팅: 디렉토리 생성, 파일 생성, navigation bar 생성
- [x] textfield + button 넣기
- [x] 토스트 팝업: 잘못된 코드, 최대 인원
