### ISSUE TITLE
[FEAT] 그룹 이미 참여 뷰 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#40]
## 💡 Issue
그룹에 이미 참여했는데 참여코드를 입력하여 다시 참여하려고 하는 경우 나오는 화면 구현
<img src="https://user-images.githubusercontent.com/81340603/199217866-66a8316a-13f7-4677-b7aa-c43f82e7d916.png" width=200px />

## 📝 Todo
- [x] 디렉토리 & 파일 생성
- [x] 타이틀 라벨 생성
- [x] 인포 라벨 생성 (컴포넌트에서 불러오기)
- [x] 하우스 이미지 어셋 추가 및 배치
- [x] 메인으로 돌아가기 메인 버튼 추가
