### ISSUE TITLE
[ADD] 프로필 사진 설정 뷰 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#45]
## 💡 Issue
<img src="https://user-images.githubusercontent.com/81340603/202444065-c950b111-2e09-48ab-a83e-dcfbbdaeb9db.png" width=200px />

## 📝 Todo
- [ ] 파일 디렉토리 만들기
- [ ] 네브바 
- [ ] title label
- [ ] 프로필 사진 Imageview
- [ ] 프로필 사진 collectionview
- [ ] main button

**Comment by Guel-git** [comment]
새로 화면을 그리지 않고 OnboardingProfile VC를 상속해오는 방식 사용함
