### ISSUE TITLE
[ADD] 하우스 관리 설정 뷰 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#47]
## 💡 Issue
<img src="https://user-images.githubusercontent.com/81340603/202451310-15656e31-af9d-4d99-b9fd-0b613fa06a52.png" width=200px />

## 📝 Todo
- [x] 파일 & 디렉토리 생성
- [x] 네브바 생성
- [x] 테이블뷰 셀 생성
- [x] 하우스에서 나가기 button 생성
- [x] 하단 디바이더 생성
- [x] 하단 라벨 버튼 생성
- [x] 말풍선 view 생성
