### ISSUE TITLE
[ADD] 알림 설정 뷰 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#51]
## 💡 Issue
<img width="332" alt="스크린샷 2022-12-19 오후 7 16 15" src="https://user-images.githubusercontent.com/81340603/208402573-afd63551-22ac-41a0-8d4e-8826c5886101.png">
푸시 알림 설정 뷰 구현

## 📝 Todo
- [x] 디렉토리 & 파일 생성
- [x] Nav bar
- [ ] Table view cell : label & 토글
- [ ] Table view 추가
