### ISSUE TITLE
[ADD] 문의하기 화면 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#53]
## 💡 Issue
<img src="https://user-images.githubusercontent.com/81340603/208459828-7b68b1b0-252c-46e0-8fd7-353aed4702da.png" width=200px />
문의하기 화면을 구현합니다

## 📝 Todo
- [x] 파일 & 디렉토리 생성
- [x] nav bar 생성
- [x] title label
- [x] cell view 생성
- [x] 인스타그램 link 연결
- [x] 메일 연동
