### ISSUE TITLE
[ADD] 집안일 생성 - 공간 선택 디폴트 화면 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#57]
## 💡 Issue
<img src="https://user-images.githubusercontent.com/81340603/210208845-a31086e1-9261-4484-974e-ae0c283703b8.png" width=200px />
집안일 생성 뷰의 디폴트 화면을 구현합니다.

## 📝 Todo
- [x] Navigation Bar
- [x] 날짜 선택 row 
- [x] 공간 선택 Collection View
- [x] 공간 선택 info label
- [x] 집안일 직접 입력하기 Button
- [x] 다음 MainButton
