### ISSUE TITLE
[ADD] 집안일선택-공간활성 화면 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#59]
## 💡 Issue
SelectHouseWork(집안일 선택) 화면에서 유저가 공간을 눌렀을 때 나오는 화면입니다.
|<img src="https://user-images.githubusercontent.com/81340603/210783042-5e53b7ce-efaa-4dba-bb17-28f77ca56179.png" width=150px />|<img src="https://user-images.githubusercontent.com/81340603/210783048-9d413ca6-815c-4f8a-9e7d-7f2f2294dadf.png" width=150px />|<img src="https://user-images.githubusercontent.com/81340603/210783054-8d8ee8a4-4903-4460-8829-7c76eaec06a7.png" width=150px />|
|:---:|:---:|:---:|
|<center>집안일 목록</center>|<center>집안일 목록 선택</center>|<center>집안일 선택 후 다른 공간 선택</center>|

## 📝 Todo
갈길이 멉니다..
- [x] Space Model에 집안일 목록 추가
- [x] SelectHouseWorkCollectionViewCell 생성
- [x] SelectHouseWorkCollectionView 생성 및 배치
- [x] 공간 선택시 InfoLabel hidden 처리하는 로직 추가
- [x] 공간 선택시 SelectHouseWorkCollectionView가 나오는 로직 추가
- [x] 공간활성 & 집안일 활성 -> 다음 버튼 활성화 하는 로직 추가
- [x] 공간활성 & 집안일 활성 상태에서 다른 공간 선택 -> Alert 띄우는 로직 추가
