### ISSUE TITLE
[ADD] 홈 화면 구현

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#60]
## 💡 Issue

**디자인**
<img width="212" alt="스크린샷 2023-01-13 오후 2 45 12" src="https://user-images.githubusercontent.com/83629193/212246252-28261a5e-a3e5-4b4c-a14d-4556377cabf9.png">

**개발 된 뷰**
<img width="238" alt="스크린샷 2023-01-15 오후 11 09 14" src="https://user-images.githubusercontent.com/83629193/212545613-204561e3-bac2-4e8d-ad0f-7fd8e64f40f7.png">

## 📝 Todo

홈 화면을 구현합니다.
- [x] 상단 뷰 구현 (top 부터 규칙 뷰)
- [x] 캘린더 뷰 화면 구현
- [ ] 캘린더 뷰에서 요일에 따른 카드 뷰 구현 (일주일 캘린더 뷰 부터 요일별 카드 뷰)
- [x] 끝낸 집안일 뷰 구현
- [x] 하단 집안일 추가 버튼 구현
- [x] 규칙 뷰 랜덤 텍스트 로직 구현
- [x] 이후 로직 추출 후 구현
