### ISSUE TITLE
[ADD] 집안일 설정_상단 DatePicker & 세부 집안일 CollectionView

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#63]
## 💡 Issue
집안일 설정 화면에서 상단 DatePicker 바와 세부 집안일 CollectionView를 구현하려고 합니다.

<img width="283" alt="스크린샷 2023-01-19 오후 3 07 22" src="https://user-images.githubusercontent.com/81340603/213368222-a2779101-2d8b-4ac8-be9e-02d3dbd9dd2e.png">

세부 집안일 CollectionView의 로직이 꽤 복잡해서 PR을 분리했습니다.

## 📝 Todo
- [x] Nav bar 제작
- [x] DatePicker / 장소 라벨 Row
- [x] SetHouseWorkCollectionViewCell 제작
- [x] SetHouseWorkCollectionView 제작
- [x] Cell에서 X 버튼 누르면 해당 cell 제거하는 로직 추가
- [x] Cell Focus 로직 추가 (기획서 참고)
- [x] 세부 집안일 입력 상태에 따라 Label textColor 달라지는 로직 추가
