### ISSUE TITLE
[ADD] 집안일 설정_담당자 화면 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#65]
## 💡 Issue
|<img src="https://user-images.githubusercontent.com/81340603/213898556-62beb074-ebb7-4828-a44c-1b83e544176c.png" width=180px />|<img src="https://user-images.githubusercontent.com/81340603/213898557-440605f6-1f5f-42a6-8103-1e2cf876f67d.png" width=180px />|<img src="https://user-images.githubusercontent.com/81340603/213898558-23942b05-eba0-4cd8-91d7-52d8386e06ce.png" width=180px />|
|:---:|:---:|:---:|
|<center>집안일 담당자 부분</center>|<center>집안일 담당자 선택</center>|<center>집안일 담당자 없음</center>|

## 📝 Todo
- [x] 담당자 라벨
- [x] MemberCollectionViewCell 구현 (Global에)
- [x] GetManagerCollectionView 구현
- [x] SelectManagerView 생성
- [x] SelectManagerCollectionView/Cell 구현
- [x] 집안일 담당자 선택 라벨과 버튼 생성
- [x] 담당자 없이 확인 버튼 터치했을 경우 토스트 팝업 보여주는 로직 추가
