### ISSUE TITLE
[ADD] 홈뷰, 주간 캘린더 뷰 내부 로직 구현

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#67]
## 💡 Issue

<img width="228" alt="스크린샷 2023-01-24 오후 4 06 19" src="https://user-images.githubusercontent.com/83629193/214231597-d97bdff1-37df-48fe-a774-e034123f2768.png"><img width="228" alt="스크린샷 2023-01-24 오후 4 06 28" src="https://user-images.githubusercontent.com/83629193/214231608-89f0abf4-18ab-45a6-8d46-f50303b911bf.png">
홈 뷰에서 주간 캘린더의 내부 로직을 구현하려합니다.

## 📝 Todo

- [x] 주간 캘린더 가로 스크롤 구현, 날짜 계산됨
- [x] 가로 스크롤에 슬라이딩 이벤트 추가
- [x] '오늘' 버튼 눌렀을 때 주간 캘린더가 오늘에 해당되는 날짜로 이동
- [x] 좌측 상단의 버튼 이벤트로 캘린더 띄우기
- [x] 좌측 상단 버튼으로 뜬 캘린더에서 날짜 선택했을 때 해당 날짜에 맞춰 홈뷰의 주간 캘린더 날짜 설정
