### ISSUE TITLE
[ADD] HomeView ScrollView Event

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#68]
## 💡 Issue

<img width="205" alt="스크린샷 2023-02-03 오후 6 05 31" src="https://user-images.githubusercontent.com/83629193/216558163-a2cd2ac5-50c7-48be-bb9a-8cec50383f67.png"><img width="205" alt="스크린샷 2023-02-03 오후 6 05 55" src="https://user-images.githubusercontent.com/83629193/216558170-035657b8-eb07-49b7-be88-cc9e0f02762e.png">
## 📝 Todo

- [x] 스크롤 뷰 하단 스크롤 이벤트 시 상단 뷰 사이즈 0
- [x] 스크롤 뷰가 스크롤 뷰의 최상단에 도달 시 상단 뷰 사이즈 원래 사이즈로 복구
- [x] 사이즈 update 하는 과정에 애니메이션 추가
