### ISSUE TITLE
[ADD] Main Button 만들기

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#7]
## 💡 Issue
공통 컴포넌트로 사용될 Main Button (CTA) 만들기

## 📝 Todo
- [x] setBackgroundColor 함수 extension으로 만들기
- [x] .normal / .disabled 에 따라 컬러 다르게 설정하기
- [x] test 용 VC 에서 적용되는지 테스트 해보기

## 📬 Reference
- []()](https://github.com/DeveloperAcademy-POSTECH/MC2-Team5-Firefighter/blob/develop/Manito/Manito/Global/UIComponent/MainButton.swift)
