### ISSUE TITLE
[ADD] 집안일 직접 입력_집안일 이름 구현

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#72]
## 💡 Issue
<img width="746" alt="스크린샷 2023-02-01 오후 7 01 52" src="https://user-images.githubusercontent.com/81340603/216012121-4da3e495-356a-4814-a319-c61b24a2cd5d.png">
집안일 직접 입력 화면에서 집안일 입력 TextField 영역까지 구현합니다.

## 📝 Todo
- [x] 파일 생성
- [x] 상단바
- [x] DatePicker / 장소 Label
- [x] 집안일 이름 Label / 잘못된 집안일 경고 Label
- [x] TextField Custom (기존에 있는 TextField enum으로 나눠서 처리)
- [x] 16자가 넘어갈 경우 Label 띄워주는 로직 만들기
