### ISSUE TITLE
[ADD] 홈_하우스 규칙 설정 뷰 구현

### ISSUE THREAD

**Issue by kimkyuchul** [fairer-iOS/fairer-iOS#75]
## 💡 Issue

<img width="219" alt="스크린샷 2023-02-06 오후 2 27 27" src="https://user-images.githubusercontent.com/25146374/216890784-3734070a-5a6d-4d91-a503-384f68539548.png">
홈 > 하우스 규칙 설정 뷰를 구현합니다.

## 📝 Todo

- [x] #76
- [x] 상단 네비바 설정
- [x]  하우스 규칙 설정 라벨 / 규칙 텍스트 필드 추가
- [x] 텍스트 필드의 x 클릭시  내용 삭제
- [x] 텍스트 필드에서 엔터 클릭시  규칙 추가 
- [x] 규칙 컬렉션 뷰 추가
- [x] x 클릭시 규칙 삭제
