### ISSUE TITLE
[ADD] 집안일 직접 입력_담당자 & 시간 설정

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#77]
## 💡 Issue
<img width="374" alt="스크린샷 2023-02-07 오후 7 52 06" src="https://user-images.githubusercontent.com/81340603/217225813-d1cafaae-fc5c-4f96-9f50-eca349969e29.png">
집안일 직접 입력 화면에서 담당자 부분과 시간 설정 부분을 구현합니다.
현재 올라와 있는 피알과 어찌보면 거의 동일해서 해당 코드 참고해서 그대로 작성하고 앞 피알 머지되면 풀 받아서 중복되는 부분 삭제할 예정입니다.

## 📝 Todo
- [ ] GetManagerView 생성
- [ ] GetManagerCollectionView & CollectionViewCell 생성
- [ ] SelectManagerView 생성
- [ ] SelectManagerCollectionView & CollectionViewCell 생성
- [ ] 시간 설정 Switch
- [ ] 시간 DatePicker
