### ISSUE TITLE
[ADD] 홈뷰, 하단 컬렉션 뷰 개발 

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#80]
## 💡 Issue

<img width="764" alt="스크린샷 2023-02-10 오후 6 32 28" src="https://user-images.githubusercontent.com/83629193/218055890-51cb9860-b176-4d55-a7aa-5751aa975d0c.png">

## 📝 Todo

- [ ] 끝낸 집안일과 못 끝낸 집안일 분리
- [ ] 못 끝낸 집안일 셀을 제스처를 통해 끝낸 집안일로 이동, 끝낸 집안일 제스처로 되돌리기 구현
- [ ] 끝낸 집안일 수에 따라 상단 텍스트 변경
- [ ] 해야할 집안일이 없는 경우 -> 아이콘으로 처리
- [ ] 모든 집안일을 끝냈을 경우 -> 아이콘으로 처리

**Comment by hongjunehuke** [comment]
스와이프 제스처 부분으로 인해
하단 컬렉션 뷰 -> 테이블 뷰로 변경 할까 합니다.
