### ISSUE TITLE
[FEAT] 네트워크 폴더링

### ISSUE THREAD

**Issue by hongjunehuke** [fairer-iOS/fairer-iOS#89]
## 💡 Issue

1. Moya를 사용하여 서버 연동 합니다.
2. DTO, Router, API 폴더를 만들고 기본적인 셋팅 합니다.
## 📝 Todo

- [x] DTO, Router, API 폴더 생성
- [x] 여러 API에서 사용하는 DTO파일 미리 생성
- [x] http 통신 세팅
