### ISSUE TITLE
[ADD] getAllPreset api 연결

### ISSUE THREAD

**Issue by Guel-git** [fairer-iOS/fairer-iOS#93]
## 💡 Issue
SelectHouseWork 화면에서 모든 공간에 해당되는 모든 세부 집안일을 불러오는 api 를 연결합니다.

## 📝 Todo
- [ ] Swagger에서 테스트 하기
- [ ] Preset Router 구현
- [ ] Preset API 구현
- [ ] Model 필요시 추가
- [ ] 화면에 Binding
